/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/analytics/': RouteRecordInfo<'/analytics/', '/analytics', Record<never, never>, Record<never, never>>,
    '/configurations/': RouteRecordInfo<'/configurations/', '/configurations', Record<never, never>, Record<never, never>>,
    '/configurations/ConfigurationList': RouteRecordInfo<'/configurations/ConfigurationList', '/configurations/ConfigurationList', Record<never, never>, Record<never, never>>,
    '/configurations/EditConfiguration': RouteRecordInfo<'/configurations/EditConfiguration', '/configurations/EditConfiguration', Record<never, never>, Record<never, never>>,
    '/error/Error404Page': RouteRecordInfo<'/error/Error404Page', '/error/Error404Page', Record<never, never>, Record<never, never>>,
    '/machines/': RouteRecordInfo<'/machines/', '/machines', Record<never, never>, Record<never, never>>,
    '/machines/MachineList': RouteRecordInfo<'/machines/MachineList', '/machines/MachineList', Record<never, never>, Record<never, never>>,
    '/machines/MachineSummaryCharts': RouteRecordInfo<'/machines/MachineSummaryCharts', '/machines/MachineSummaryCharts', Record<never, never>, Record<never, never>>,
    '/miners/': RouteRecordInfo<'/miners/', '/miners', Record<never, never>, Record<never, never>>,
    '/miners/MinerList': RouteRecordInfo<'/miners/MinerList', '/miners/MinerList', Record<never, never>, Record<never, never>>,
    '/overview/': RouteRecordInfo<'/overview/', '/overview', Record<never, never>, Record<never, never>>,
    '/pipelines/': RouteRecordInfo<'/pipelines/', '/pipelines', Record<never, never>, Record<never, never>>,
    '/pipelines/SectorList': RouteRecordInfo<'/pipelines/SectorList', '/pipelines/SectorList', Record<never, never>, Record<never, never>>,
    '/storages/': RouteRecordInfo<'/storages/', '/storages', Record<never, never>, Record<never, never>>,
    '/storages/StoragePathList': RouteRecordInfo<'/storages/StoragePathList', '/storages/StoragePathList', Record<never, never>, Record<never, never>>,
    '/storages/StorageUsageChart': RouteRecordInfo<'/storages/StorageUsageChart', '/storages/StorageUsageChart', Record<never, never>, Record<never, never>>,
  }
}
