/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/analytics/': RouteRecordInfo<'/analytics/', '/analytics', Record<never, never>, Record<never, never>>,
    '/configurations/': RouteRecordInfo<'/configurations/', '/configurations', Record<never, never>, Record<never, never>>,
    '/configurations/ConfigurationList': RouteRecordInfo<'/configurations/ConfigurationList', '/configurations/ConfigurationList', Record<never, never>, Record<never, never>>,
    '/configurations/EditConfiguration': RouteRecordInfo<'/configurations/EditConfiguration', '/configurations/EditConfiguration', Record<never, never>, Record<never, never>>,
    '/error/Error404Page': RouteRecordInfo<'/error/Error404Page', '/error/Error404Page', Record<never, never>, Record<never, never>>,
    '/machines/': RouteRecordInfo<'/machines/', '/machines', Record<never, never>, Record<never, never>>,
    '/machines/MachineList': RouteRecordInfo<'/machines/MachineList', '/machines/MachineList', Record<never, never>, Record<never, never>>,
    '/machines/MachineSummaryCharts': RouteRecordInfo<'/machines/MachineSummaryCharts', '/machines/MachineSummaryCharts', Record<never, never>, Record<never, never>>,
    '/overview/': RouteRecordInfo<'/overview/', '/overview', Record<never, never>, Record<never, never>>,
    '/pipelines/': RouteRecordInfo<'/pipelines/', '/pipelines', Record<never, never>, Record<never, never>>,
    '/pipelines/SectorList': RouteRecordInfo<'/pipelines/SectorList', '/pipelines/SectorList', Record<never, never>, Record<never, never>>,
    '/storages/': RouteRecordInfo<'/storages/', '/storages', Record<never, never>, Record<never, never>>,
    '/storages/StoragePathList': RouteRecordInfo<'/storages/StoragePathList', '/storages/StoragePathList', Record<never, never>, Record<never, never>>,
    '/storages/StorageUsageChart': RouteRecordInfo<'/storages/StorageUsageChart', '/storages/StorageUsageChart', Record<never, never>, Record<never, never>>,
    '/widgets/chart/ChartPage': RouteRecordInfo<'/widgets/chart/ChartPage', '/widgets/chart/ChartPage', Record<never, never>, Record<never, never>>,
    '/widgets/chart/components/AcquisitionChannels': RouteRecordInfo<'/widgets/chart/components/AcquisitionChannels', '/widgets/chart/components/AcquisitionChannels', Record<never, never>, Record<never, never>>,
    '/widgets/chart/components/AnalyticsReport': RouteRecordInfo<'/widgets/chart/components/AnalyticsReport', '/widgets/chart/components/AnalyticsReport', Record<never, never>, Record<never, never>>,
    '/widgets/chart/components/ChartCards': RouteRecordInfo<'/widgets/chart/components/ChartCards', '/widgets/chart/components/ChartCards', Record<never, never>, Record<never, never>>,
    '/widgets/chart/components/IncomeCompare': RouteRecordInfo<'/widgets/chart/components/IncomeCompare', '/widgets/chart/components/IncomeCompare', Record<never, never>, Record<never, never>>,
    '/widgets/chart/components/IncomeOverview': RouteRecordInfo<'/widgets/chart/components/IncomeOverview', '/widgets/chart/components/IncomeOverview', Record<never, never>, Record<never, never>>,
    '/widgets/chart/components/SalesReport': RouteRecordInfo<'/widgets/chart/components/SalesReport', '/widgets/chart/components/SalesReport', Record<never, never>, Record<never, never>>,
    '/widgets/chart/components/UniqueVisitor': RouteRecordInfo<'/widgets/chart/components/UniqueVisitor', '/widgets/chart/components/UniqueVisitor', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/ActiveTickets': RouteRecordInfo<'/widgets/data/components/ActiveTickets', '/widgets/data/components/ActiveTickets', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/ApplicationSales': RouteRecordInfo<'/widgets/data/components/ApplicationSales', '/widgets/data/components/ApplicationSales', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/FeedList': RouteRecordInfo<'/widgets/data/components/FeedList', '/widgets/data/components/FeedList', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/IncomingRequest': RouteRecordInfo<'/widgets/data/components/IncomingRequest', '/widgets/data/components/IncomingRequest', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/LatestCustomer': RouteRecordInfo<'/widgets/data/components/LatestCustomer', '/widgets/data/components/LatestCustomer', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/LatestOrder': RouteRecordInfo<'/widgets/data/components/LatestOrder', '/widgets/data/components/LatestOrder', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/LatestPosts': RouteRecordInfo<'/widgets/data/components/LatestPosts', '/widgets/data/components/LatestPosts', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/MessageList': RouteRecordInfo<'/widgets/data/components/MessageList', '/widgets/data/components/MessageList', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/NewCustomers': RouteRecordInfo<'/widgets/data/components/NewCustomers', '/widgets/data/components/NewCustomers', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/ProductSales': RouteRecordInfo<'/widgets/data/components/ProductSales', '/widgets/data/components/ProductSales', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/ProjectList': RouteRecordInfo<'/widgets/data/components/ProjectList', '/widgets/data/components/ProjectList', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/RecentTickets': RouteRecordInfo<'/widgets/data/components/RecentTickets', '/widgets/data/components/RecentTickets', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/TaskList': RouteRecordInfo<'/widgets/data/components/TaskList', '/widgets/data/components/TaskList', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/TeamMembers': RouteRecordInfo<'/widgets/data/components/TeamMembers', '/widgets/data/components/TeamMembers', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/TodoList': RouteRecordInfo<'/widgets/data/components/TodoList', '/widgets/data/components/TodoList', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/TotalRevenue': RouteRecordInfo<'/widgets/data/components/TotalRevenue', '/widgets/data/components/TotalRevenue', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/TrafficSources': RouteRecordInfo<'/widgets/data/components/TrafficSources', '/widgets/data/components/TrafficSources', Record<never, never>, Record<never, never>>,
    '/widgets/data/components/UserActivity': RouteRecordInfo<'/widgets/data/components/UserActivity', '/widgets/data/components/UserActivity', Record<never, never>, Record<never, never>>,
    '/widgets/data/DataPage': RouteRecordInfo<'/widgets/data/DataPage', '/widgets/data/DataPage', Record<never, never>, Record<never, never>>,
    '/widgets/statistics/components/SkillCard': RouteRecordInfo<'/widgets/statistics/components/SkillCard', '/widgets/statistics/components/SkillCard', Record<never, never>, Record<never, never>>,
    '/widgets/statistics/components/TaskCard': RouteRecordInfo<'/widgets/statistics/components/TaskCard', '/widgets/statistics/components/TaskCard', Record<never, never>, Record<never, never>>,
    '/widgets/statistics/components/WidgetFive': RouteRecordInfo<'/widgets/statistics/components/WidgetFive', '/widgets/statistics/components/WidgetFive', Record<never, never>, Record<never, never>>,
    '/widgets/statistics/StatisticsPage': RouteRecordInfo<'/widgets/statistics/StatisticsPage', '/widgets/statistics/StatisticsPage', Record<never, never>, Record<never, never>>,
  }
}
