package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/strahe/curio-dashboard/graph"
	"github.com/strahe/curio-dashboard/graph/model"
)

// ID is the resolver for the id field.
func (r *pipelineResolver) ID(ctx context.Context, obj *model.Pipeline) (string, error) {
	return fmt.Sprintf("%d-%d", obj.SpID, obj.SectorNumber), nil
}

// Pipeline returns graph.PipelineResolver implementation.
func (r *Resolver) Pipeline() graph.PipelineResolver { return &pipelineResolver{r} }

type pipelineResolver struct{ *Resolver }
