package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"time"

	"github.com/strahe/curio-dashboard/graph"
	"github.com/strahe/curio-dashboard/graph/cache_control"
	"github.com/strahe/curio-dashboard/graph/model"
)

// Locations is the resolver for the locations field.
func (r *sectorResolver) Locations(ctx context.Context, obj *model.Sector) ([]*model.SectorLocation, error) {
	cache_control.SetHint(ctx, cache_control.ScopePrivate, time.Minute*5)
	return r.loader.SectorLocations(ctx, obj.SpID, obj.SectorNum)
}

// Tasks is the resolver for the tasks field.
func (r *sectorResolver) Tasks(ctx context.Context, obj *model.Sector) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: Tasks - tasks"))
}

// TaskHistories is the resolver for the taskHistories field.
func (r *sectorResolver) TaskHistories(ctx context.Context, obj *model.Sector) ([]*model.TaskHistory, error) {
	panic(fmt.Errorf("not implemented: TaskHistories - taskHistories"))
}

// Sector returns graph.SectorResolver implementation.
func (r *Resolver) Sector() graph.SectorResolver { return &sectorResolver{r} }

type sectorResolver struct{ *Resolver }
