// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/strahe/curio-dashboard/types"
)

type ActorDeadline struct {
	Empty      bool `json:"empty"`
	Current    bool `json:"current"`
	Proven     bool `json:"proven"`
	PartFaulty bool `json:"partFaulty"`
	Faulty     bool `json:"faulty"`
}

type MachineDetail struct {
	ID          int       `json:"id"`
	MachineName string    `json:"machineName"`
	Tasks       string    `json:"tasks"`
	TasksArray  []string  `json:"tasksArray,omitempty"`
	Layers      string    `json:"layers"`
	LayersArray []string  `json:"layersArray,omitempty"`
	StartupTime time.Time `json:"startupTime"`
	Miners      string    `json:"miners"`
	MinersArray []string  `json:"minersArray,omitempty"`
	MachineID   int       `json:"machineId"`
}

type MiningSummaryDay struct {
	Day  time.Time     `json:"day"`
	SpID types.ActorID `json:"sp_id"`
	Won  int           `json:"won"`
}

type NodeInfo struct {
	ID                   string `json:"id"`
	Address              string `json:"address"`
	Reachability         bool   `json:"reachability"`
	Epoch                int    `json:"epoch"`
	Behind               int    `json:"behind"`
	PeersToPublishMsgs   int    `json:"peersToPublishMsgs"`
	PeersToPublishBlocks int    `json:"peersToPublishBlocks"`
	Version              string `json:"version"`
}

type Pipeline struct {
	ID                       string          `json:"id"`
	SpID                     types.ActorID   `json:"spId"`
	SectorNumber             int             `json:"sectorNumber"`
	CreateTime               time.Time       `json:"createTime"`
	RegSealProof             int             `json:"regSealProof"`
	TicketEpoch              *int            `json:"ticketEpoch,omitempty"`
	TicketValue              types.ByteArray `json:"ticketValue,omitempty"`
	TaskIDSdr                *int            `json:"taskIdSdr,omitempty"`
	AfterSdr                 bool            `json:"afterSdr"`
	TreeDCid                 *string         `json:"treeDCid,omitempty"`
	TaskIDTreeD              *int            `json:"taskIdTreeD,omitempty"`
	AfterTreeD               bool            `json:"afterTreeD"`
	TaskIDTreeC              *int            `json:"taskIdTreeC,omitempty"`
	AfterTreeC               bool            `json:"afterTreeC"`
	TreeRCid                 *string         `json:"treeRCid,omitempty"`
	TaskIDTreeR              *int            `json:"taskIdTreeR,omitempty"`
	AfterTreeR               bool            `json:"afterTreeR"`
	PrecommitMsgCid          *string         `json:"precommitMsgCid,omitempty"`
	TaskIDPrecommitMsg       *int            `json:"taskIdPrecommitMsg,omitempty"`
	AfterPrecommitMsg        bool            `json:"afterPrecommitMsg"`
	SeedEpoch                *int            `json:"seedEpoch,omitempty"`
	PrecommitMsgTsk          types.ByteArray `json:"precommitMsgTsk,omitempty"`
	AfterPrecommitMsgSuccess bool            `json:"afterPrecommitMsgSuccess"`
	SeedValue                types.ByteArray `json:"seedValue,omitempty"`
	TaskIDPorep              *int            `json:"taskIdPorep,omitempty"`
	PorepProof               types.ByteArray `json:"porepProof,omitempty"`
	AfterPorep               bool            `json:"afterPorep"`
	TaskIDFinalize           *int            `json:"taskIdFinalize,omitempty"`
	AfterFinalize            bool            `json:"afterFinalize"`
	TaskIDMoveStorage        *int            `json:"taskIdMoveStorage,omitempty"`
	AfterMoveStorage         bool            `json:"afterMoveStorage"`
	CommitMsgCid             *string         `json:"commitMsgCid,omitempty"`
	TaskIDCommitMsg          *int            `json:"taskIdCommitMsg,omitempty"`
	AfterCommitMsg           bool            `json:"afterCommitMsg"`
	CommitMsgTsk             types.ByteArray `json:"commitMsgTsk,omitempty"`
	AfterCommitMsgSuccess    bool            `json:"afterCommitMsgSuccess"`
	Failed                   bool            `json:"failed"`
	FailedAt                 *time.Time      `json:"failedAt,omitempty"`
	FailedReason             string          `json:"failedReason"`
	FailedReasonMsg          string          `json:"failedReasonMsg"`
	Status                   PipelineStatus  `json:"status"`
}

type Query struct {
}

type StoragePath struct {
	ID            string      `json:"id"`
	StorageID     string      `json:"storageId"`
	Type          StorageType `json:"type"`
	Urls          string      `json:"urls"`
	Weight        int         `json:"weight"`
	MaxStorage    int         `json:"maxStorage"`
	CanSeal       bool        `json:"canSeal"`
	CanStore      bool        `json:"canStore"`
	Groups        *string     `json:"groups,omitempty"`
	AllowTo       *string     `json:"allowTo,omitempty"`
	AllowTypes    *string     `json:"allowTypes,omitempty"`
	DenyTypes     *string     `json:"denyTypes,omitempty"`
	Capacity      int         `json:"capacity"`
	Available     int         `json:"available"`
	FsAvailable   int         `json:"fsAvailable"`
	Reserved      int         `json:"reserved"`
	Used          int         `json:"used"`
	LastHeartbeat time.Time   `json:"lastHeartbeat"`
	HeartbeatErr  *string     `json:"heartbeatErr,omitempty"`
	AllowMiners   string      `json:"allowMiners"`
	DenyMiners    string      `json:"denyMiners"`
}

type StorageStats struct {
	Type             StorageType `json:"type"`
	TotalCapacity    int         `json:"totalCapacity"`
	TotalAvailable   int         `json:"totalAvailable"`
	TotalUsed        int         `json:"totalUsed"`
	TotalReserved    int         `json:"totalReserved"`
	TotalFsAvailable int         `json:"totalFsAvailable"`
}

type StorageUsage struct {
	Time        time.Time `json:"time"`
	Available   int       `json:"available"`
	Used        int       `json:"used"`
	Reserved    int       `json:"reserved"`
	FsAvailable int       `json:"fsAvailable"`
}

type TaskHistory struct {
	ID                     int       `json:"id"`
	TaskID                 int       `json:"taskId"`
	Name                   string    `json:"name"`
	Posted                 time.Time `json:"posted"`
	WorkStart              time.Time `json:"workStart"`
	WorkEnd                time.Time `json:"workEnd"`
	Result                 bool      `json:"result"`
	Err                    *string   `json:"err,omitempty"`
	CompletedByHostAndPort string    `json:"completedByHostAndPort"`
}

type TaskNameAggregate struct {
	Name    string `json:"name"`
	Total   int    `json:"total"`
	Success int    `json:"success"`
	Failure int    `json:"failure"`
}

type TaskSummary struct {
	Name       string `json:"name"`
	TrueCount  int    `json:"trueCount"`
	FalseCount int    `json:"falseCount"`
	TotalCount int    `json:"totalCount"`
}

type TaskSummaryDay struct {
	Day        time.Time `json:"day"`
	TrueCount  int       `json:"trueCount"`
	FalseCount int       `json:"falseCount"`
	TotalCount int       `json:"totalCount"`
}

type PipelineStatus string

const (
	PipelineStatusStarted      PipelineStatus = "Started"
	PipelineStatusSdr          PipelineStatus = "SDR"
	PipelineStatusTreeD        PipelineStatus = "TreeD"
	PipelineStatusTreeC        PipelineStatus = "TreeC"
	PipelineStatusTreeR        PipelineStatus = "TreeR"
	PipelineStatusPreCommit    PipelineStatus = "PreCommit"
	PipelineStatusPreCommitMsg PipelineStatus = "PreCommitMsg"
	PipelineStatusPoRep        PipelineStatus = "PoRep"
	PipelineStatusFinalize     PipelineStatus = "Finalize"
	PipelineStatusMoveStorage  PipelineStatus = "MoveStorage"
	PipelineStatusCommit       PipelineStatus = "Commit"
	PipelineStatusCommitMsg    PipelineStatus = "CommitMsg"
	PipelineStatusFailed       PipelineStatus = "Failed"
)

var AllPipelineStatus = []PipelineStatus{
	PipelineStatusStarted,
	PipelineStatusSdr,
	PipelineStatusTreeD,
	PipelineStatusTreeC,
	PipelineStatusTreeR,
	PipelineStatusPreCommit,
	PipelineStatusPreCommitMsg,
	PipelineStatusPoRep,
	PipelineStatusFinalize,
	PipelineStatusMoveStorage,
	PipelineStatusCommit,
	PipelineStatusCommitMsg,
	PipelineStatusFailed,
}

func (e PipelineStatus) IsValid() bool {
	switch e {
	case PipelineStatusStarted, PipelineStatusSdr, PipelineStatusTreeD, PipelineStatusTreeC, PipelineStatusTreeR, PipelineStatusPreCommit, PipelineStatusPreCommitMsg, PipelineStatusPoRep, PipelineStatusFinalize, PipelineStatusMoveStorage, PipelineStatusCommit, PipelineStatusCommitMsg, PipelineStatusFailed:
		return true
	}
	return false
}

func (e PipelineStatus) String() string {
	return string(e)
}

func (e *PipelineStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PipelineStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PipelineStatus", str)
	}
	return nil
}

func (e PipelineStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type StorageType string

const (
	StorageTypeHybrid   StorageType = "Hybrid"
	StorageTypeSeal     StorageType = "Seal"
	StorageTypeStore    StorageType = "Store"
	StorageTypeReadonly StorageType = "Readonly"
)

var AllStorageType = []StorageType{
	StorageTypeHybrid,
	StorageTypeSeal,
	StorageTypeStore,
	StorageTypeReadonly,
}

func (e StorageType) IsValid() bool {
	switch e {
	case StorageTypeHybrid, StorageTypeSeal, StorageTypeStore, StorageTypeReadonly:
		return true
	}
	return false
}

func (e StorageType) String() string {
	return string(e)
}

func (e *StorageType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StorageType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StorageType", str)
	}
	return nil
}

func (e StorageType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
