/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/configs/': RouteRecordInfo<'/configs/', '/configs', Record<never, never>, Record<never, never>>,
    '/deals/': RouteRecordInfo<'/deals/', '/deals', Record<never, never>, Record<never, never>>,
    '/machines/': RouteRecordInfo<'/machines/', '/machines', Record<never, never>, Record<never, never>>,
    '/miners/': RouteRecordInfo<'/miners/', '/miners', Record<never, never>, Record<never, never>>,
    '/pipelines/': RouteRecordInfo<'/pipelines/', '/pipelines', Record<never, never>, Record<never, never>>,
    '/sectors/': RouteRecordInfo<'/sectors/', '/sectors', Record<never, never>, Record<never, never>>,
    '/sectors/[sp]-[id]': RouteRecordInfo<'/sectors/[sp]-[id]', '/sectors/:sp-:id', { sp: ParamValue<true>, id: ParamValue<true> }, { sp: ParamValue<false>, id: ParamValue<false> }>,
    '/storages/': RouteRecordInfo<'/storages/', '/storages', Record<never, never>, Record<never, never>>,
    '/tasks/': RouteRecordInfo<'/tasks/', '/tasks', Record<never, never>, Record<never, never>>,
  }
}
